# Generated by Django 4.2.7 on 2023-11-21 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_team_user_is_admin_user_team"),
        ("tasks", "0003_alter_task_created_by"),
    ]

    operations = []
