# Generated by Django 4.2.7 on 2023-11-16 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_remove_user_is_admin_remove_user_team_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="membership", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
