# Generated by Django 4.2.6 on 2023-12-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_spent',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
