# Generated by Django 4.2.6 on 2023-11-22 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_assigned_to_alter_task_created_by'),
        ('tasks', '0006_team_members'),
    ]

    operations = [
    ]
