# Generated by Django 4.2.6 on 2023-12-03 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_activity_log_activity_log_activity_log_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_log',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
