# Generated by Django 4.2.6 on 2023-12-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_reminder_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reminder_days',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
