# Generated by Django 4.2.6 on 2023-12-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_usertimespent'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertimespent',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
