# Generated by Django 4.2.6 on 2023-12-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_usertimespent_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertimespent',
            name='timestamp',
        ),
    ]
