# Generated by Django 4.2.6 on 2023-12-08 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='user_notified',
        ),
    ]
