# Generated by Django 4.2.6 on 2023-12-08 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_rename_user_notification_user_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user_notified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
