# Generated by Django 4.2.6 on 2023-12-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_timelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time_spent',
        ),
    ]
