# Generated by Django 4.2.6 on 2023-12-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_notification_user_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reminder_days',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
