# Generated by Django 4.2.6 on 2023-12-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_task_reminder_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unread_notifications',
            field=models.IntegerField(default=0),
        ),
    ]
