# Generated by Django 4.2.6 on 2023-12-08 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_user_unread_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='seen',
        ),
    ]
