# Generated by Django 4.2.6 on 2023-12-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_remove_notification_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unread_notifications',
            field=models.IntegerField(default=1),
        ),
    ]
