# Generated by Django 4.2.6 on 2023-12-08 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_activity_log_user'),
        ('tasks', '0011_remove_task_time_spent'),
        ('tasks', '0014_alter_user_unread_notifications'),
    ]

    operations = [
    ]
