# Generated by Django 4.2.6 on 2023-12-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_remove_user_unread_notifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTimeSpent',
            new_name='TimeSpent',
        ),
    ]
