# Generated by Django 4.2.6 on 2023-12-09 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_rename_usertimespent_timespent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='logged_time',
            field=models.BigIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='timespent',
            name='time_spent',
            field=models.BigIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
