# Generated by Django 4.2.6 on 2023-12-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_alter_timelog_logged_time_alter_timespent_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
