# Generated by Django 4.2.6 on 2023-12-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_remove_task_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
