# Generated by Django 4.2.6 on 2023-12-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_alter_task_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
