# Generated by Django 4.2.6 on 2023-12-11 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_alter_task_seen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
